### ISSUE TITLE
Array schemas are not single schemas

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/metadata#9]
https://github.com/OpenEnergyPlatform/metadata/blob/07daaeca24c2841ed6af1af5f0a0efad4a55859b/metadata/v140/schema.json#L27

From what I understand from the JSON-Schema standard, this is not a valid construct. The value of items can only be a single schema. The same seems to be the case for keywords.

**Comment by 4lm** [comment]
@MGlauer, if I validate schema v140 against the newest schema draft (v7) schema everything seems fine ("No errors found. JSON validates against the schema"): https://www.jsonschemavalidator.net/

Or maybe I don't get what you're saying? Do you mean that the array should be named "languages" (plural) and the single items in the array should be named "language" (singular)?

Could you give me an example of how you would structure above mentioned construct?

**Comment by 4lm** [comment]
@MGlauer, maybe I know what you meant, this:

```
        "language": {
            "description": "[...]",
            "type": "array",
            "items": {
                "language": {
                    "description": "TBD",
                    "type": [ "string", "null" ]
                }
            }
        }
```

Could maybe be written as:

```
        "language": {
            "description": "[...]",
            "type": "array",
            "items": {
                    "type": [ "string", "null" ]
                }
            }
        }
```

Will test it tomorrow against our v140 example. This could clear a lot of the TBDs as well!

**Comment by MGlauer** [comment]
> @MGlauer, if I validate schema v140 against the newest schema draft (v7) everything seems fine ("No errors found. JSON validates against the schema"): https://www.jsonschemavalidator.net/

I also found this tool but I am not really sure how to use it. Regardless of the selected schema, the input 

```
{
  "completely-madeup-key": {}
}
```
Results in "No errors found. JSON validates against the schema", too. But maybe that is a user problem ^^'

**Comment by MGlauer** [comment]
> @MGlauer, maybe I know what you meant, this:
> 
> ```
>         "language": {
>             "description": "[...]",
>             "type": "array",
>             "items": {
>                 "language": {
>                     "description": "TBD",
>                     "type": [ "string", "null" ]
>                 }
>             }
>         }
> ```
> 
> Could maybe be written as:
> 
> ```
>         "language": {
>             "description": "[...]",
>             "type": "array",
>             "items": {
>                     "type": [ "string", "null" ]
>                 }
>             }
>         }
> ```
> 
> Will test it tomorrow against our v140 example. This could clear a lot of the TBDs as well!

Yes, that. Sorry for the imprecission

**Comment by Bachibouzouk** [comment]
> Results in "No errors found. JSON validates against the schema", too. But maybe that is a user problem ^^'

There should be an option to reject other keys than the one presented

**Comment by 4lm** [comment]
> @MGlauer: Results in "No errors found. JSON validates against the schema", too. But maybe that is a user problem ^^'

The reference states that it's ok for:
- arrays:  "to not provide all of the items": https://json-schema.org/understanding-json-schema/reference/array.html
- objects : "leaving out properties is valid": https://json-schema.org/understanding-json-schema/reference/object.html?highlight=required#properties

> @Bachibouzouk: There should be an option to reject other keys than the one presented

Yes, by making them "required" (properties in object): https://json-schema.org/understanding-json-schema/reference/object.html?highlight=required#required-properties 

**IMO it also makes sense to add "required" fields to objects in our schemas - will try it out!**

PS: It's also possible to use enums (property/item), demand Unique items (items in array).
PPS: In arrays a special order of data types can be set, plus defining the data type of additional values, but also restricting min/max values in array. So it's also very flexibel.

**Comment by Bachibouzouk** [comment]
> Yes, by making them "required" (properties in object)

@4lm I beg to disagree: making some properties "required" will not prevent user to add additional properties. To prevent this you have to set ["additionalProperties"](https://json-schema.org/understanding-json-schema/reference/object.html#additionalproperties) to false

You can also set "minProperties" to the number of fields, so that they will automatically be all required :)

**Comment by 4lm** [comment]
> @4lm I beg to disagree: making some properties "required" will not prevent user to add additional properties. To prevent this you have to set "additionalProperties" to false

Yes @Bachibouzouk, that's a good idea - will use it!

But IMO the "required" yes/no question is not fully answered, because:

[I'm talking v1.4.0 only right now]

1.  In some of the descriptions there is defined, that if a certain object is given, certain properties must be included, e. g.: "Every contributor must have a title and property".
2. In the example and template json files every possible property seems filled and in the example file also `null` as type is used. The template files uses empty strings (""). Also in some of the schema descriptions the creator/user is (inconsistently) asked to enter "null" or "none". IMO this raises the question which entity is responsible to handle all this (`null`, "", "null", "none"). I think, "yes, I agree" the user should not be bothered to enter all possible data perfectly into an interface. But there should be a mechanism which creates a metadata json, in which the data input of "", "null" and "none" is translated into `null` types and also translates non entered properties to `null`. BUT this requirement is IMO out of scope concerning the metadata schema and should not be forced by using "required" in this case. This case is IMO a good use case for [omi](https://github.com/OpenEnergyPlatform/omi). So long story short @Bachibouzouk, I agree with you on this one :wink:.

So IMO only in case one "required" should be used!

**Comment by 4lm** [comment]
Side thought: Also, not using "required" on every property enables mandatory properties (above use case one). Otherwise every property would be mandatory, which fights the purpose of having mandatory fields!

**Comment by MGlauer** [comment]
> > @4lm I beg to disagree: making some properties "required" will not prevent user to add additional properties. To prevent this you have to set "additionalProperties" to false
> 
> Yes @Bachibouzouk, that's a good idea - will use it!
> 
> But IMO the "required" yes/no question is not fully answered, because:
> 
> [I'm talking v1.4.0 only right now]
> 
> 1. In some of the descriptions there is defined, that if a certain object is given, certain properties must be included, e. g.: "Every contributor must have a title and property".

I think @Ludee mentioned at some point that no field should be mandatory. But one remark: There is a semantic difference between the following two objects:
```
A = {`sourceOfFunding`: None}
B = {}
```
In case of `A`, we know that there is no source of funding, whilst in case of `B` there is no information about a funding source.

> 2. In the example and template json files every possible property seems filled and in the example file also `null` as type is used. The template files uses empty strings (""). Also in some of the schema descriptions the creator/user is (inconsistently) asked to enter "null" or "none". IMO this raises the question which entity is responsible to handle all this (`null`, "", "null", "none"). I think, "yes, I agree" the user should not be bothered to enter all possible data perfectly into an interface. But there should be a mechanism which creates a metadata json, in which the data input of "", "null" and "none" is translated into `null` types and also translates non entered properties to `null`. BUT this requirement is IMO out of scope concerning the metadata schema and should not be forced by using "required" in this case. This case is IMO a good use case for [omi](https://github.com/OpenEnergyPlatform/omi). So long story short @Bachibouzouk, I agree with you on this one wink.

I don't think that this is not something any tool can or should attempt to do. The semantics of null, "", "null", "none" are all different and may be intended:

* `null`: Nothing, literally, i.e. there is no entry here and the user means that there is really *nothing*  
* `""`: The empty string. I do not really see any proper use-case where this might be intended but the important difference is that `null != null`, whilst `"" == ""`. This is an important difference especially when LOD is involved. I have no yacht, I presume @4lm has no yacht either. If null is encoded as `""` this would entail that both of us have the same yacht, whilst an encoding as `null` does not have the same consequence.
* `"null"` (or `"none"`): Literally the string "null" - I might have a model that is called "null".

I agree, that a tool implementing OEP metadata should handle those cases but not by translating blindly, but by communicating those consequences to the user and give him the option to choose.

> 
> So IMO only in case one "required" should be used!

**Comment by 4lm** [comment]
> I think @Ludee mentioned at some point that no field should be mandatory.

Interesting, IMO there should be some mandatory fields for minimal basic information (like in zenodo.org) otherwise the metadata makes little sense and also for the above mentioned use case one (in which the description defines some mandatory properties as a "must" if a certain object is given). I will work on this and make a branch PR, which we then can modify or throw away if necessary.

> There is a semantic difference between the following two object. [...] In case of A, we know that there is no source of funding, whilst in case of B there is no information about a funding source.

Yes, you're totally right, thanks for reminding me!

> I don't think that this is not something any tool can or should attempt to do. The semantics of null, "", "null", "none" are all different and may be intended. [...] I agree, that a tool implementing OEP metadata should handle those cases but not by translating blindly, but by communicating those consequences to the user and give him the option to choose.

Yes, I agree again! We should be careful because of the implied semantics by blindly translating stuff, so I correct my opinion! @MGlauer, thanks for clearly laying this out!

What do you think about enums?
 https://github.com/OpenEnergyPlatform/metadata/issues/4#issuecomment-551914561

**Comment by Ludee** [comment]
I think this can be closed? Reopen if still valid!
